jazyková korektúra -> inklúzia
faktaoklimatu/web-sk pull request #13
Opened 2021-02-10 13:43 UTC by LenkaSedlackova

2021-02-10 17:55 UTC, mukrop requested changes
Toto podla mna nie je spravne, vid https://jazykovaporadna.sme.sk/q/2749/
Preco si myslis, ze tam ma byt makke i?

2021-02-11 16:31 UTC, LenkaSedlackova commented
myslím to ako množné číslo (vy). informovanÝ je iba mužský rod

2021-02-11 16:44 UTC, mukrop commented
To nie je mnozne cislo, ale vykanie. A podla jazykovednej poradne (ten link, co som prikladal vyssie) ma vykanie mnozne cislo v slovesach, ale pouziva jednotne cislo v mennych slovnych druhoch. Alebo som to zle pochopil?

2021-02-11 16:51 UTC, LenkaSedlackova commented
čítala som jazykovednú poradňu :) všetky príklady sú tam uvedené pre jednotné číslo a zároveň sa píše, že: Kým určitý slovesný tvar je pri vykaní vždy v množnom čísle, nominálne slovné druhy sú v jednotnom čísle, napr. podstatné meno: Vy ste majsterka (majster); prídavné meno: Pani Smutná, boli ste spokojná s našou prácou? – Pane, boli ste spokojný s našou prácou?

teda ak chceš vykať žene, mal by si vykať Ak chcete byť informovanÁ. Preto som navrhla inkluzívny tvar Ak chcete byť (všetci) informovanÍ. prípadne by sa to dalo riešiť "informovaný/informovaná" a pod. tiež nenapíšeš "študenti, boli ste spokojný s prednáškou", aj keď im vykáš. už sa chápeme? :)

2021-02-11 16:59 UTC, mukrop commented
OK, uz rosumiem, akym sposobom tam tu inkluziu myslis. Tym padom asi OK.

2021-02-11 16:59 UTC, mukrop approved these changes

2021-02-11 16:59 UTC, merged