uholny-phaseout-eu
faktaoklimatu/web-sk pull request #42
Opened 2021-05-23 13:30 UTC by vrq-github

2021-05-29 19:27 UTC, mukrop commented
Aky je tu stav? Moj odhad je, ze to este nepreslo korekturami (?) a vidim, ze tam este nie je nahrana infografika (preto aj padaju testy).
Tym padom sa rusim ako _asignee_, oznacte ma na review, ked to bude ready :-).

2021-05-30 11:52 UTC, vrq-github commented
Vo štvrtok máme s Kristy call a zbehneme tam všetko co pozostávalo. Phase
out incl.

Dňa so 29. 5. 2021, 21:27 Martin Ukrop ***@***.***>
napísal(a):

> Aky je tu stav? Moj odhad je, ze to este nepreslo korekturami (?) a vidim,
> ze tam este nie je nahrana infografika (preto aj padaju testy).
> Tym padom sa rusim ako *asignee*, oznacte ma na review, ked to bude ready
> :-).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/faktaoklimatu/web-sk/pull/42#issuecomment-850887103>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASNGY2IWQFE7SONBY6KYONLTQE5ZXANCNFSM45LW2T2Q>
> .
>

2021-05-30 12:09 UTC, mukrop commented
Super, dik za info.

2021-10-14 08:46 UTC, vrq-github commented
Tuto musím počkať na Kristi, napísala som jej, tak sa snáď už stretneme časovo

2021-11-12 13:46 UTC, LenkaSedlackova commented
> 
> 
> Tuto musím počkať na Kristi, napísala som jej, tak sa snáď už stretneme časovo

@vrq-github prosím ťa, čo s týmto? vidím na GDrive infografiku z jari, mali ste nakoniec ten call s Kristi?

2021-12-14 11:47 UTC, mukrop requested changes
Temer hotovo, ale par veci este zostava:
* [ ] V texte je formulacia k cenam povolenie, ktora je kvoli plynutiu casu uz nespravna. Vid https://github.com/faktaoklimatu/web-cz/issues/976
* [ ] Neviem odhadut, ako velmi sa situacia zmenila vdaka COP26. Ak sa to menilo, nemali by sme tam doplnit nejaky disclaimer ako sa diskutuje v https://github.com/faktaoklimatu/web-cz/issues/952?

Vedel by sa mi na oboje pozriet napriklad Tom @protivinsky?

2021-12-22 13:25 UTC, LenkaSedlackova commented
>     * [ ]  V texte je formulacia k cenam povolenie, ktora je kvoli plynutiu casu uz nespravna. Vid [faktaoklimatu/web-cz#976](https://github.com/faktaoklimatu/web-cz/issues/976)

ja som sa toto v SVK verzii už snažila fixnúť, pozerala som ceny kvót kdesi

2021-12-25 16:42 UTC, protivinsky commented
Co se tyce nevyresenych otazek:
- Cena povolenky: ta informace, ktera je v textu, dnes jiz rozhodne nedava smysl, cili to by urcite chtelo aktualizovat. Nevim, kdo vlastne pripravoval tu ceskou verzi explaineru a premyslim, jaky postup dava nejvetsi smysl - asi proste prepsat ten odstavec v CZ verzi a pote prelozit do SK? Navic si myslim, ze pri soucasnych cenach povolenek nemuze byt uhli dlouhodobe profitabilni, nehlede na jakakoli politicka jednani. Takze podle me uhelny phase-out v zasade do cca 5-10 let probehne z ekonomickych duvodu vsude, kde energetika spada pod EU ETS.
- Zaverecna komunikace COP26 rika, ze potrebujeme phase-down of coal and phase-out of inefficient fossil fuel subsidies. Ale nic konkretnejsiho pro evropske zeme tam podle me nebylo.

2021-12-26 17:18 UTC, mukrop commented
Ako sme si pisali na Slacku, priprav prosim opravu pre cesky web a potom to prelozime do slovenskeho.

Inak zacali sme pouzivat varovny infobox pre casovo viazane infornacie, vid https://faktaoklimatu.cz/explainery/pozice-akteru-cop Ak uznas za vhodne, mozes take niecio zakomponovat do upravy.

Dlhodobo totiz nemozme mat vsetko 100% aktualne, to nejde. Ak presne cisla nie su nutne, smeroval by som k tomu pisat texty "nadcasovo" a konkretnym (napriklad cenam povoleniek) sa skor vyhybal. Ak su konkretne cisla uzitocne/nutne, pisal by som to hned viazane na datum (akoze "situacia k datumu XX bola taka a taka" napisat uz pocas vydania).

2022-01-01 16:05 UTC, mukrop commented
@LenkaSedlackova, novy odstavec navrhnuty v https://github.com/faktaoklimatu/web-cz/pull/982, budem rad za preklad.

2022-01-02 19:13 UTC, LenkaSedlackova commented
hotofson

2022-01-04 20:20 UTC, mukrop approved these changes

2022-01-04 20:20 UTC, merged