CZ verzia + kus prekladu
faktaoklimatu/web-sk pull request #56
Opened 2021-11-12 14:48 UTC by LenkaSedlackova

chýba iba Komentáre k cenám - odrážka 2 (ceny v Kč)

2021-11-18 13:42 UTC, vrq-github commented
Cena energie opravena na MWh a opravena o Lenkine ceny https://drive.google.com/drive/folders/1xHI_MPHbLRqLNTNgfeBQgNJI2RIKKhz5

2021-12-12 15:12 UTC, mukrop requested changes
Temer hotovo, este tam stale chyba prelozeny jeden odstavec, ktory cakal, kym sa rozhodnu a dotiahnu prepocty cien na eura.

Mozem poprosit @LenkaSedlackova o dotiahnutie? (Predpokladam, ze to bude uz rychle.)

2021-12-21 18:55 UTC, LenkaSedlackova commented
@jankrcal ty si autorom, prosím? 
- nevieš, odkiaľ je ten rozdiel v cene za kWh pre carbon-capture/bez carbon-capture uhoľné elektrárne? nenašla som k tomu čísla v českom datasete ani
- predpokladám správne, že cena emisných povoleniek je rovnaká pre ČR aj pre SR? sa tam píše, že v ČR sa pripočítava cca 1 Kč/kWh, tak uvažujem, či to môžem iba jednoducho prepočítať na €/MWh (bo máme graf v MWh)

2021-12-21 18:57 UTC, LenkaSedlackova commented
@jankrcal ty si autorom, prosím? 
- nevieš, odkiaľ je ten rozdiel v cene za kWh pre carbon-capture/bez carbon-capture uhoľné elektrárne? nenašla som k tomu čísla v českom datasete ani
- predpokladám správne, že cena emisných povoleniek je rovnaká pre ČR aj pre SR? sa tam píše, že v ČR sa pripočítava cca 1 Kč/kWh, tak uvažujem, či to môžem iba jednoducho prepočítať na €/MWh (bo máme graf v MWh)

2021-12-21 23:08 UTC, LenkaSedlackova commented
+ prosím o kontrolu prepočtu z Kč/kWh na €/MWh, počítala som kurz 1 € = 25 Kč pre jednoduchosť

2021-12-22 19:29 UTC, jankrcal commented
Ne ne, to dělal Vojta Rujbr, zeptej se ho prosím na Slacku.

Ad povolenky, ano, ty mají stejnou cenu jako v Česku, jen se ta cena od vydání české verze výrazně změnila :)
Povolenky teď stojí asi 80 EUR na tunu, na 1kWh z hnědého uhlí potřebuješ skoro 1kg CO2, tedy 80 euro centů.
Možná by bylo fajn do toho slovenskýho textu dát maličko víc vysvětlení, aby si to člověk mohl snadno aktualizovat, třeba přidat "(při současné ceně 80 EUR / t CO2)".

2021-12-24 09:08 UTC, LenkaSedlackova commented
za nás s Vojtom ok

2021-12-26 18:09 UTC, mukrop approved these changes
Skontrolovane, dik za preklad a korektury :-).

2021-12-26 18:11 UTC, merged