Emisie eu poradie
faktaoklimatu/web-sk pull request #57
Opened 2021-11-12 15:29 UTC by LenkaSedlackova

dataset snáď ready na publikovanie

2021-11-17 12:03 UTC, mukrop requested changes
Na hruby odhad to vyzera OK, ale este tam chyba subor s infografikou, ktoru okrem datasetu pridavas.

2021-11-18 09:26 UTC, LenkaSedlackova commented
myslíš toto či niečo iné? v [CZ repe](https://github.com/faktaoklimatu/web-cz/tree/master/_datasets) sú samé .md súbory, tak netuším, o čo sa jedná
![image](https://user-images.githubusercontent.com/56084968/142387930-233c42a7-a329-41b5-9e47-50daa950bdb5.png)

2021-11-18 18:49 UTC, mukrop commented
Nie, to nemyslim (ale to tam tiez je treba pridat).

V zalozke "Files changed" vdis, ze okrem MD datasetu si pridala este MD `_infographics/emisie/emisie-eu-poradie.md`.

2021-11-29 14:38 UTC, LenkaSedlackova commented
@vrq-github mohla by si prosím nahrať SK verziu [tejto infografiky](https://faktaoklimatu.cz/infografiky/emise-eu-poradi) do branchu emisie-eu-poradie?
zostáva teda
- [ ] nahrať IG @vrq-github 
- [ ] review od @mukrop

2021-12-14 10:44 UTC, mukrop approved these changes

2021-12-14 10:49 UTC, merged