Elektrina na Slovensku (Sankey diagram)
faktaoklimatu/web-sk pull request #67
Opened 2021-12-12 15:24 UTC by mukrop

Preview verzia webu:

Chyba dokoncit:
* [ ] Novy text (teraz je tam cesky). Minimalne zdroje su ine, asi aj nejake sprievodne info je ine (text uz asi niekde je?).
* [ ] Prelozit text do slovenciny (asi uz je tiez niekde urobene?).
* [ ] Finalna kontrola.

2021-12-20 22:05 UTC, jankrcal approved these changes
Díky!

2021-12-21 23:11 UTC, LenkaSedlackova requested changes
@jankrcal prosím kuk na ten import/export, ako čom sme si písali

2021-12-22 19:16 UTC, jankrcal commented
Lenko, trochu mi nesedělo navázání sdělení, podívej se prosím na moji drobnou úpravu, jestli jsem to jazykově nerozbil:

https://github.com/faktaoklimatu/web-sk/pull/67/commits/f9c5b5f34f537cf1edb3f00e18995047d3576c32

2021-12-23 09:06 UTC, mukrop commented
> Lenko, trochu mi nesedělo navázání sdělení, podívej se prosím na moji drobnou úpravu, jestli jsem to jazykově nerozbil:
> 
> [f9c5b5f](https://github.com/faktaoklimatu/web-sk/commit/f9c5b5f34f537cf1edb3f00e18995047d3576c32)

Ja som to skontroloval, vsetko v pohode :-).

2021-12-23 09:09 UTC, merged